/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medis;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KHSCI5MCA16126
 */
public class doctor_page extends javax.swing.JFrame {
    
    public static String doctorID;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form doctor_page
     * @param userId
     */
    public doctor_page(String userId) {
        initComponents();
        doctorID = userId;
        loadProfile();
    }
    public String dname;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sex = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        medis = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        sidePanel = new javax.swing.JPanel();
        doctor = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        UploadPhoto = new javax.swing.JLabel();
        doctPanel = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        patient = new javax.swing.JLabel();
        patientPanel = new javax.swing.JPanel();
        patientInfo = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        profile_panel = new javax.swing.JPanel();
        doctProfile = new javax.swing.JPanel();
        doctName = new javax.swing.JLabel();
        doctDesignation = new javax.swing.JLabel();
        member = new javax.swing.JLabel();
        detailsPanel = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        gmailLabel = new javax.swing.JLabel();
        gmail = new javax.swing.JLabel();
        contactNoLabel = new javax.swing.JLabel();
        contactNo = new javax.swing.JLabel();
        profileUpdatePanel = new javax.swing.JPanel();
        updateProfileLabel = new javax.swing.JLabel();
        dnameLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        dGenderLabel = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        dGmailLabel = new javax.swing.JLabel();
        gmailTxt = new javax.swing.JTextField();
        dContactNoLabel = new javax.swing.JLabel();
        contactNoTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        patient_details = new javax.swing.JPanel();
        detTopPanel = new javax.swing.JPanel();
        patientLabel = new javax.swing.JLabel();
        addPatientPanel = new javax.swing.JPanel();
        patientIdLabel = new javax.swing.JLabel();
        patientId = new javax.swing.JTextField();
        patientNameLabel = new javax.swing.JLabel();
        patientName = new javax.swing.JTextField();
        phoneNoLabel = new javax.swing.JLabel();
        phoneNo = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        sexLabel = new javax.swing.JLabel();
        patMale = new javax.swing.JRadioButton();
        patFemale = new javax.swing.JRadioButton();
        mailLabel = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        diseaseLabel = new javax.swing.JLabel();
        diseaseScrollPane = new javax.swing.JScrollPane();
        disease = new javax.swing.JTextArea();
        medicineLabel = new javax.swing.JLabel();
        medicineScrollPane = new javax.swing.JScrollPane();
        medicine = new javax.swing.JTextArea();
        addPatientBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        patientTablePanel = new javax.swing.JPanel();
        patientDetails = new javax.swing.JLabel();
        patiScrollPane = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        historyPanel = new javax.swing.JPanel();
        patientsPanel = new javax.swing.JPanel();
        patients = new javax.swing.JLabel();
        patientScrollPane = new javax.swing.JScrollPane();
        patientTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(102, 102, 102));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medis.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        medis.setForeground(new java.awt.Color(255, 255, 255));
        medis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medis.setText("MEDIS");
        topPanel.add(medis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 60, 34));

        closeBtn.setBackground(new java.awt.Color(236, 35, 35));
        closeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("X");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        topPanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 30));

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 30));

        sidePanel.setBackground(new java.awt.Color(51, 51, 51));
        sidePanel.setForeground(new java.awt.Color(51, 51, 51));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctor.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        doctor.setForeground(new java.awt.Color(204, 204, 204));
        doctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctor.setText("DOCTOR");
        sidePanel.add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 64, 29));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/user (2).png"))); // NOI18N
        sidePanel.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        UploadPhoto.setForeground(new java.awt.Color(204, 204, 204));
        UploadPhoto.setText("Upload photo");
        sidePanel.add(UploadPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        doctPanel.setBackground(new java.awt.Color(153, 153, 153));
        doctPanel.setForeground(new java.awt.Color(153, 153, 153));

        profile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/user (3).png"))); // NOI18N
        profile.setText("  PROFILE");
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docprofileclicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/logout.png"))); // NOI18N
        logout.setText("  LOG OUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout doctPanelLayout = new javax.swing.GroupLayout(doctPanel);
        doctPanel.setLayout(doctPanelLayout);
        doctPanelLayout.setHorizontalGroup(
            doctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(doctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        doctPanelLayout.setVerticalGroup(
            doctPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(profile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(24, 24, 24))
        );

        sidePanel.add(doctPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, -1));

        patient.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        patient.setText("  PATIENT ");
        sidePanel.add(patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        patientPanel.setBackground(new java.awt.Color(153, 153, 153));

        patientInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        patientInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/information.png"))); // NOI18N
        patientInfo.setText("  PATIENT INFO");
        patientInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient_info(evt);
            }
        });

        history.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/history.png"))); // NOI18N
        history.setText("  HISTORY");
        history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout patientPanelLayout = new javax.swing.GroupLayout(patientPanel);
        patientPanel.setLayout(patientPanelLayout);
        patientPanelLayout.setHorizontalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(history, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        patientPanelLayout.setVerticalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(patientInfo)
                .addGap(39, 39, 39)
                .addComponent(history)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        sidePanel.add(patientPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, -1));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 530));

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        doctProfile.setBackground(new java.awt.Color(51, 51, 51));
        doctProfile.setForeground(new java.awt.Color(51, 51, 51));

        doctName.setForeground(new java.awt.Color(255, 255, 255));
        doctName.setText(" DR SULU(example)");

        doctDesignation.setForeground(new java.awt.Color(255, 255, 255));
        doctDesignation.setText(" CARDIOLOGIST(example)");

        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setText("MEMBER");

        javax.swing.GroupLayout doctProfileLayout = new javax.swing.GroupLayout(doctProfile);
        doctProfile.setLayout(doctProfileLayout);
        doctProfileLayout.setHorizontalGroup(
            doctProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctProfileLayout.createSequentialGroup()
                .addGroup(doctProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(doctName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(doctProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(doctProfileLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(member))
                        .addGroup(doctProfileLayout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(doctDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        doctProfileLayout.setVerticalGroup(
            doctProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctProfileLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(doctName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(member, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        detailsPanel.setBackground(new java.awt.Color(153, 153, 153));

        aboutLabel.setText("ABOUT");

        positionLabel.setText("Position");

        position.setText("Cardiologist(Example)");

        genderLabel.setText("Gender");

        gender.setText("Male(EX)");

        gmailLabel.setText("Gmail");

        gmail.setText("suluthedoc@gmail.com(EX)");

        contactNoLabel.setText("Contact Number");

        contactNo.setText("9999883412(EX)");

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addComponent(aboutLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gmailLabel)
                            .addComponent(genderLabel)
                            .addComponent(contactNoLabel)
                            .addComponent(positionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gmail, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(aboutLabel)
                .addGap(36, 36, 36)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel)
                    .addComponent(position))
                .addGap(36, 36, 36)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(gender))
                .addGap(33, 33, 33)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gmailLabel)
                    .addComponent(gmail))
                .addGap(37, 37, 37)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNoLabel)
                    .addComponent(contactNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profileUpdatePanel.setBackground(new java.awt.Color(204, 204, 204));

        updateProfileLabel.setText("Update Profile");

        dnameLabel.setText("Name");

        dGenderLabel.setText("Gender");

        sex.add(rdMale);
        rdMale.setText("male");

        sex.add(rdFemale);
        rdFemale.setText("female");

        dGmailLabel.setText("Gmail");

        dContactNoLabel.setText("Contact Number");

        updateBtn.setText("Update");
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profileUpdatePanelLayout = new javax.swing.GroupLayout(profileUpdatePanel);
        profileUpdatePanel.setLayout(profileUpdatePanelLayout);
        profileUpdatePanelLayout.setHorizontalGroup(
            profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileUpdatePanelLayout.createSequentialGroup()
                .addGroup(profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileUpdatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateProfileLabel))
                    .addGroup(profileUpdatePanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(updateBtn))
                    .addGroup(profileUpdatePanelLayout.createSequentialGroup()
                        .addGroup(profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profileUpdatePanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dGenderLabel)
                                    .addComponent(dnameLabel)
                                    .addComponent(dGmailLabel))
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileUpdatePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dContactNoLabel)
                                .addGap(34, 34, 34)))
                        .addGroup(profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(profileUpdatePanelLayout.createSequentialGroup()
                                .addComponent(rdMale)
                                .addGap(18, 18, 18)
                                .addComponent(rdFemale))
                            .addComponent(gmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        profileUpdatePanelLayout.setVerticalGroup(
            profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileUpdatePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(updateProfileLabel)
                .addGap(51, 51, 51)
                .addGroup(profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dnameLabel)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdMale)
                    .addComponent(rdFemale)
                    .addComponent(dGenderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dGmailLabel)
                    .addComponent(gmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(profileUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dContactNoLabel)
                    .addComponent(contactNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(updateBtn)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout profile_panelLayout = new javax.swing.GroupLayout(profile_panel);
        profile_panel.setLayout(profile_panelLayout);
        profile_panelLayout.setHorizontalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profileUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        profile_panelLayout.setVerticalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doctProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLayeredPane2.add(profile_panel, "card2");

        detTopPanel.setBackground(new java.awt.Color(102, 102, 102));

        patientLabel.setText("ADD PATIENT");

        javax.swing.GroupLayout detTopPanelLayout = new javax.swing.GroupLayout(detTopPanel);
        detTopPanel.setLayout(detTopPanelLayout);
        detTopPanelLayout.setHorizontalGroup(
            detTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detTopPanelLayout.setVerticalGroup(
            detTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detTopPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(patientLabel)
                .addContainerGap())
        );

        addPatientPanel.setBackground(new java.awt.Color(153, 153, 153));

        patientIdLabel.setText("Patient ID");

        patientNameLabel.setText("Patient Name");

        phoneNoLabel.setText("Phone no");

        ageLabel.setText("Age");

        sexLabel.setText("Gender");

        sex.add(patMale);
        patMale.setText("Male");

        sex.add(patFemale);
        patFemale.setText("Female");

        mailLabel.setText("Gmail");

        diseaseLabel.setText("Disease");

        disease.setColumns(20);
        disease.setRows(5);
        diseaseScrollPane.setViewportView(disease);

        medicineLabel.setText("Medicine");

        medicine.setColumns(20);
        medicine.setRows(5);
        medicineScrollPane.setViewportView(medicine);

        addPatientBtn.setText("ADD");
        addPatientBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("CLEAR");
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPatientPanelLayout = new javax.swing.GroupLayout(addPatientPanel);
        addPatientPanel.setLayout(addPatientPanelLayout);
        addPatientPanelLayout.setHorizontalGroup(
            addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPatientPanelLayout.createSequentialGroup()
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientIdLabel)
                            .addComponent(patientNameLabel)
                            .addComponent(phoneNoLabel))
                        .addGap(33, 33, 33)
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneNo)
                            .addComponent(age)
                            .addGroup(addPatientPanelLayout.createSequentialGroup()
                                .addComponent(patMale, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(patFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatientPanelLayout.createSequentialGroup()
                        .addComponent(medicineLabel)
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPatientPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addPatientBtn)
                                .addGap(48, 48, 48)
                                .addComponent(clearBtn))
                            .addGroup(addPatientPanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(medicineScrollPane))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatientPanelLayout.createSequentialGroup()
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diseaseLabel)
                            .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ageLabel)
                                .addComponent(sexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mail)
                            .addComponent(diseaseScrollPane))))
                .addContainerGap())
        );
        addPatientPanelLayout.setVerticalGroup(
            addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patMale)
                    .addComponent(patFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailLabel)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diseaseScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diseaseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPatientPanelLayout.createSequentialGroup()
                        .addComponent(medicineScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearBtn)
                            .addComponent(addPatientBtn)))
                    .addComponent(medicineLabel))
                .addGap(21, 21, 21))
        );

        patientTablePanel.setBackground(new java.awt.Color(102, 102, 102));

        patientDetails.setText("PATIENT DETAILS");

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Name", "Ph no", "Disease", "Medicine"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        patiScrollPane.setViewportView(patientTable);

        javax.swing.GroupLayout patientTablePanelLayout = new javax.swing.GroupLayout(patientTablePanel);
        patientTablePanel.setLayout(patientTablePanelLayout);
        patientTablePanelLayout.setHorizontalGroup(
            patientTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientTablePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientDetails)
                .addGap(365, 365, 365))
            .addGroup(patientTablePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(patiScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        patientTablePanelLayout.setVerticalGroup(
            patientTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientTablePanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(patientDetails)
                .addGap(53, 53, 53)
                .addComponent(patiScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout patient_detailsLayout = new javax.swing.GroupLayout(patient_details);
        patient_details.setLayout(patient_detailsLayout);
        patient_detailsLayout.setHorizontalGroup(
            patient_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patient_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(patient_detailsLayout.createSequentialGroup()
                        .addComponent(addPatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        patient_detailsLayout.setVerticalGroup(
            patient_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patient_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.add(patient_details, "card3");

        patientsPanel.setBackground(new java.awt.Color(102, 102, 102));

        patients.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        patients.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patients.setText("PATIENTS");

        patientTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "Name", "Phone No", "Disease", "Medicine"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        patientScrollPane.setViewportView(patientTable2);

        javax.swing.GroupLayout patientsPanelLayout = new javax.swing.GroupLayout(patientsPanel);
        patientsPanel.setLayout(patientsPanelLayout);
        patientsPanelLayout.setHorizontalGroup(
            patientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGroup(patientsPanelLayout.createSequentialGroup()
                        .addComponent(patients, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        patientsPanelLayout.setVerticalGroup(
            patientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientsPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(patients, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(patientScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane2.add(historyPanel, "card4");

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 800, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void check(){
        try{
            con = my_sql_connect.connectdb();
            pst = con.prepareStatement("select docPswd from doctor where docID=?");
            pst.setString(1, doctorID);
            rs = pst.executeQuery();
            String password = rs.getString("docPswd");
            if("password".equals(password)){
                this.setVisible(false);
                PasswordConfirmation pswdConfirm = new PasswordConfirmation("doctor",doctorID);
                pswdConfirm.setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e);
        }
    }
    
    private void loadProfile(){
        String id, password, designtn="", gendr="", phno="", status="", email="";
        try{
            con=my_sql_connect.connectdb();
            pst = con.prepareStatement("select * from doctor where docID=?");
            pst.setString(1, doctorID);
            rs = pst.executeQuery();
            if(rs.next()){                
                id = rs.getString(1);
                password = rs.getString(2);
                dname = rs.getString(3);
                designtn = rs.getString(4);
                gendr = rs.getString(5);
                phno = String.valueOf(rs.getLong(6));
                status = rs.getString(7);
                email = rs.getString(8);
            }
            doctName.setText("DR. "+dname.toUpperCase());
            doctDesignation.setText(designtn.toUpperCase());
            position.setText(designtn);
            gender.setText(gendr);
            gmail.setText(email);
            contactNo.setText(phno);       
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Exception : "+e);
        }
    }
    
    private void docprofileclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docprofileclicked
      this.profile_panel.setVisible(true);
      this.patient_details.setVisible(false);
      this.historyPanel.setVisible(false);
    }//GEN-LAST:event_docprofileclicked

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void patient_info(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_info
       this.profile_panel.setVisible(false);
       this.patient_details.setVisible(true);
       this.historyPanel.setVisible(false);
    }//GEN-LAST:event_patient_info

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String name, gendr, mail1;
        long phno;
        name = nameTxt.getText();
        mail1 = gmailTxt.getText();
        phno = Long.parseLong(contactNoTxt.getText());
        if(rdMale.isSelected()){
            gendr = "Male";
        }
        else{
            gendr = "Female";
        }
        try{
            con=my_sql_connect.connectdb();
            pst=con.prepareStatement("update doctor set DocName=?, Gender=?, Gmail=?, PhoneNo=? where DocID=?");
            pst.setString(1, name);
            pst.setString(2, gendr);
            pst.setString(3, mail1);
            pst.setLong(4, phno);
            pst.setString(5, doctorID);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Profile Updated....");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBtnActionPerformed
        // TODO add your handling code here:
        try{
        con=my_sql_connect.connectdb();
        String id, name, gendr, email, diseases, medicines, docName ,medIssued;
        int ageCurr;
        long phno;
        
        id = patientId.getText().toLowerCase();
        name = patientName.getText();
        phno = Long.parseLong(phoneNo.getText());
        ageCurr = Integer.parseInt(age.getText());
        if(patMale.isSelected()){
            gendr = "Male";
        }
        else{
            gendr = "Female";
        }
        email = mail.getText();
        diseases = disease.getText();
        medicines = medicine.getText();
        docName = dname;
        medIssued = "No";
        if(id != null || !id.equals("")){
            pst=con.prepareStatement("insert into patient values (?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, id);
            pst.setString(2, "password");
            pst.setString(3, name);
            pst.setLong(4, phno);
            pst.setInt(5, ageCurr);
            pst.setString(6, gendr);
            pst.setString(7, email);
            pst.setString(8, diseases);
            pst.setString(9, medicines);
            pst.setString(10, docName);
            pst.setString(11, medIssued);
            int rslt = pst.executeUpdate();
            if(rslt == 1){
                DefaultTableModel tablemodel= (DefaultTableModel)patientTable.getModel();
                tablemodel.addRow(new Object[]{id,name,phno,diseases,medicines});
                clearBtnActionPerformed(evt);
                JOptionPane.showMessageDialog(null, " Patient Added... ");                
            }
            else{
                JOptionPane.showMessageDialog(null,"Patient ID already exist.");
            }
            con.close();
        }
        else{
            JOptionPane.showMessageDialog(null, "Enter valid details.");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e);
        }
    }//GEN-LAST:event_addPatientBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here
        patientId.setText(null);
        patientName.setText(null);
        phoneNo.setText(null);
        age.setText(null);
        sex.clearSelection();
        mail.setText(null);
        disease.setText(null);
        medicine.setText(null);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseClicked
        this.profile_panel.setVisible(false);
        this.patientsPanel.setVisible(false);
        this.historyPanel.setVisible(true);
    }//GEN-LAST:event_historyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new doctor_page(doctorID).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UploadPhoto;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JButton addPatientBtn;
    private javax.swing.JPanel addPatientPanel;
    private javax.swing.JTextField age;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel contactNo;
    private javax.swing.JLabel contactNoLabel;
    private javax.swing.JTextField contactNoTxt;
    private javax.swing.JLabel dContactNoLabel;
    private javax.swing.JLabel dGenderLabel;
    private javax.swing.JLabel dGmailLabel;
    private javax.swing.JPanel detTopPanel;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JTextArea disease;
    private javax.swing.JLabel diseaseLabel;
    private javax.swing.JScrollPane diseaseScrollPane;
    private javax.swing.JLabel dnameLabel;
    private javax.swing.JLabel doctDesignation;
    private javax.swing.JLabel doctName;
    private javax.swing.JPanel doctPanel;
    private javax.swing.JPanel doctProfile;
    private javax.swing.JLabel doctor;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel gmail;
    private javax.swing.JLabel gmailLabel;
    private javax.swing.JTextField gmailTxt;
    private javax.swing.JLabel history;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JLabel icon;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextArea medicine;
    private javax.swing.JLabel medicineLabel;
    private javax.swing.JScrollPane medicineScrollPane;
    private javax.swing.JLabel medis;
    private javax.swing.JLabel member;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JRadioButton patFemale;
    private javax.swing.JRadioButton patMale;
    private javax.swing.JScrollPane patiScrollPane;
    private javax.swing.JLabel patient;
    private javax.swing.JLabel patientDetails;
    private javax.swing.JTextField patientId;
    private javax.swing.JLabel patientIdLabel;
    private javax.swing.JLabel patientInfo;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JTextField patientName;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JPanel patientPanel;
    private javax.swing.JScrollPane patientScrollPane;
    private javax.swing.JTable patientTable;
    private javax.swing.JTable patientTable2;
    private javax.swing.JPanel patientTablePanel;
    private javax.swing.JPanel patient_details;
    private javax.swing.JLabel patients;
    private javax.swing.JPanel patientsPanel;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JLabel position;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel profileUpdatePanel;
    private javax.swing.JPanel profile_panel;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.ButtonGroup sex;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel updateProfileLabel;
    // End of variables declaration//GEN-END:variables
}
