/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medis;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author KHSCI5MCA16126
 */
public class patlogin extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form doclogin
     */
    public patlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        patLoginPanel = new javax.swing.JPanel();
        patiLoginLabel = new javax.swing.JLabel();
        patientBG = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        patLoginLabel = new javax.swing.JLabel();
        patientId = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        patientPassword = new javax.swing.JPasswordField();
        patientLogin = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        loginBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 2, true));
        backPanel.setPreferredSize(new java.awt.Dimension(300, 500));
        backPanel.setLayout(null);

        patLoginPanel.setBackground(new java.awt.Color(34, 117, 117));
        patLoginPanel.setPreferredSize(new java.awt.Dimension(300, 500));
        patLoginPanel.setLayout(null);

        patiLoginLabel.setBackground(new java.awt.Color(204, 102, 255));
        patiLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patiLoginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/PATIENTCONFRM.png"))); // NOI18N
        patiLoginLabel.setOpaque(true);
        patLoginPanel.add(patiLoginLabel);
        patiLoginLabel.setBounds(60, 140, 183, 95);

        patientBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/dialo_background.jpg"))); // NOI18N
        patientBG.setText("jLabel3");
        patLoginPanel.add(patientBG);
        patientBG.setBounds(0, 0, 300, 400);

        backPanel.add(patLoginPanel);
        patLoginPanel.setBounds(0, 0, 300, 400);

        login.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Login");
        backPanel.add(login);
        login.setBounds(300, 40, 300, 50);

        patLoginLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        patLoginLabel.setText("Patient ID");
        backPanel.add(patLoginLabel);
        patLoginLabel.setBounds(330, 110, 110, 30);

        patientId.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        patientId.setForeground(new java.awt.Color(153, 51, 255));
        patientId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 117, 117), 2, true));
        backPanel.add(patientId);
        patientId.setBounds(330, 140, 190, 40);

        passwordLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        passwordLabel.setText("Password");
        backPanel.add(passwordLabel);
        passwordLabel.setBounds(330, 210, 140, 30);

        patientPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 117, 117), 2, true));
        backPanel.add(patientPassword);
        patientPassword.setBounds(330, 240, 190, 40);

        patientLogin.setBackground(new java.awt.Color(204, 204, 255));
        patientLogin.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        patientLogin.setText("Login");
        patientLogin.setBorder(null);
        patientLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientLoginActionPerformed(evt);
            }
        });
        backPanel.add(patientLogin);
        patientLogin.setBounds(380, 310, 90, 40);

        closeBtn.setBackground(new java.awt.Color(255, 51, 51));
        closeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("X");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_button(evt);
            }
        });
        backPanel.add(closeBtn);
        closeBtn.setBounds(560, 0, 40, 20);

        loginBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/dialo_background.jpg"))); // NOI18N
        loginBG.setText("jLabel2");
        backPanel.add(loginBG);
        loginBG.setBounds(300, 0, 300, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(600, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_button
        dispose();
    }//GEN-LAST:event_close_button

    private void patientLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientLoginActionPerformed
        // TODO add your handling code here:

        con=my_sql_connect.connectdb();
        String sq="Select * from patient where patID = ?";
        
        String patient_id = patientId.getText().toLowerCase();
        String patient_password = String.copyValueOf(patientPassword.getPassword());     
                              
            try
            {
                pst=con.prepareStatement(sq);
                pst.setString(1,patient_id);
                rs=pst.executeQuery();

                if(rs.next()) 
                {
                    if(patient_id.equals(rs.getString(1)) && patient_password.equals(rs.getString(2)))
                    {
                        //JOptionPane.showMessageDialog(null,"WELCOME ADMIN");
                        patient_page patient=new patient_page(patient_id);
                        patient.setVisible(true);
                    } 
                }                   
                else
                {
                     JOptionPane.showMessageDialog(null,"INVALID USERNAME/PASSWORD","Access Denied...",JOptionPane.ERROR_MESSAGE);   
                }
                patientPassword.setText(null);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }        
    }//GEN-LAST:event_patientLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel login;
    private javax.swing.JLabel loginBG;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel patLoginLabel;
    private javax.swing.JPanel patLoginPanel;
    private javax.swing.JLabel patiLoginLabel;
    private javax.swing.JLabel patientBG;
    private javax.swing.JTextField patientId;
    private javax.swing.JButton patientLogin;
    private javax.swing.JPasswordField patientPassword;
    // End of variables declaration//GEN-END:variables
}
