/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medis;

import java.sql.*;
import javax.swing.*;
/**
 *
 * @author KHSCI5MCA16126
 */
public class pharmacy_login extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
    
     */
    public pharmacy_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        pharmacyPanel = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        pharmacy = new javax.swing.JLabel();
        pharmBGl = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        pharmIDLabel = new javax.swing.JLabel();
        pharmacistId = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        pharmacistPassword = new javax.swing.JPasswordField();
        pharmacistLogin = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        loginBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 2, true));
        backPanel.setPreferredSize(new java.awt.Dimension(300, 500));
        backPanel.setLayout(null);

        pharmacyPanel.setBackground(new java.awt.Color(255, 255, 255));
        pharmacyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pharmacyPanel.setPreferredSize(new java.awt.Dimension(300, 500));
        pharmacyPanel.setLayout(null);

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/pharm_logo1.jpg"))); // NOI18N
        pharmacyPanel.add(icon);
        icon.setBounds(70, 100, 160, 160);

        pharmacy.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pharmacy.setForeground(new java.awt.Color(255, 255, 255));
        pharmacy.setText("PHARMACY ");
        pharmacyPanel.add(pharmacy);
        pharmacy.setBounds(90, 260, 123, 30);

        pharmBGl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/dialo_background.jpg"))); // NOI18N
        pharmBGl.setText("jLabel7");
        pharmacyPanel.add(pharmBGl);
        pharmBGl.setBounds(0, 0, 300, 400);

        backPanel.add(pharmacyPanel);
        pharmacyPanel.setBounds(0, 0, 300, 400);

        loginLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");
        backPanel.add(loginLabel);
        loginLabel.setBounds(300, 40, 300, 50);

        pharmIDLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        pharmIDLabel.setText("Pharmacist ID");
        backPanel.add(pharmIDLabel);
        pharmIDLabel.setBounds(330, 110, 110, 30);

        pharmacistId.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        pharmacistId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 2, true));
        backPanel.add(pharmacistId);
        pharmacistId.setBounds(330, 140, 190, 40);

        passwordLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        passwordLabel.setText("Password");
        backPanel.add(passwordLabel);
        passwordLabel.setBounds(330, 210, 140, 30);

        pharmacistPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 2, true));
        backPanel.add(pharmacistPassword);
        pharmacistPassword.setBounds(330, 240, 190, 40);

        pharmacistLogin.setBackground(new java.awt.Color(204, 204, 255));
        pharmacistLogin.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pharmacistLogin.setText("Login");
        pharmacistLogin.setBorder(null);
        pharmacistLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacistLoginActionPerformed(evt);
            }
        });
        backPanel.add(pharmacistLogin);
        pharmacistLogin.setBounds(400, 320, 90, 40);

        closeBtn.setBackground(new java.awt.Color(255, 0, 0));
        closeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("X");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_button(evt);
            }
        });
        backPanel.add(closeBtn);
        closeBtn.setBounds(560, 0, 40, 20);

        loginBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medis/icons/dialo_background.jpg"))); // NOI18N
        loginBG.setText("jLabel3");
        backPanel.add(loginBG);
        loginBG.setBounds(300, 0, 300, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(600, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_button
        dispose();
    }//GEN-LAST:event_close_button

    private void pharmacistLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacistLoginActionPerformed
        // TODO add your handling code here:

        con=my_sql_connect.connectdb();
        String sq="Select * from pharmacy where phrmstID = ?";
        
        String pharmacist_id=pharmacistId.getText().toLowerCase();
        String pharmacist_password= String.copyValueOf(pharmacistPassword.getPassword());     
                              
            try
            {
                pst=con.prepareStatement(sq);
                pst.setString(1,pharmacist_id);
                rs=pst.executeQuery();

                if(rs.next()) {
                    if(pharmacist_id.equals(rs.getString(1)) && pharmacist_password.equals(rs.getString(2)))
                    {
                        //JOptionPane.showMessageDialog(null,"WELCOME ");
                        pharmacy_page pharm = new pharmacy_page(pharmacist_id);
                        pharm.setVisible(true);
                    }                     
                }                   
                else {
                     JOptionPane.showMessageDialog(null,"INVALID USERNAME/PASSWORD","Access denied...",JOptionPane.ERROR_MESSAGE);   
                }
                pharmacistPassword.setText(null);
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }        
    }//GEN-LAST:event_pharmacistLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharmacy_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pharmacy_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pharmacy_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pharmacy_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pharmacy_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel loginBG;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel pharmBGl;
    private javax.swing.JLabel pharmIDLabel;
    private javax.swing.JTextField pharmacistId;
    private javax.swing.JButton pharmacistLogin;
    private javax.swing.JPasswordField pharmacistPassword;
    private javax.swing.JLabel pharmacy;
    private javax.swing.JPanel pharmacyPanel;
    // End of variables declaration//GEN-END:variables
}
